#!/bin/bash
# Installs the newsletter digest as a macOS launchd user agent that runs
# Wednesdays and Fridays at 08:00 (a run missed while the Mac slept starts on
# wake). See SETUP.md for the full picture.
#
# Everything launchd needs at spawn time lives under ~/Library, which iCloud
# does not sync: the venv, the generated runner script and the log. The repo
# itself sits in iCloud-synced ~/Documents, where "Optimize Mac Storage"
# evicts idle files to dataless placeholders that a launchd process cannot
# read (EDEADLK), so the runner rematerializes what it needs before starting
# Python.
#
# Re-run any time; it replaces the existing job. Uninstall with:
#   launchctl bootout "gui/$(id -u)/com.bexperiments.newsletter-digest"
#   rm ~/Library/LaunchAgents/com.bexperiments.newsletter-digest.plist
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
LABEL="com.bexperiments.newsletter-digest"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
APP_DIR="$HOME/Library/Application Support/newsletter-digest"
VENV_DIR="$APP_DIR/.venv"
RUNNER="$APP_DIR/run.sh"
LOG_DIR="$HOME/Library/Logs/newsletter-digest"
LOG_FILE="$LOG_DIR/digest.log"
KEYCHAIN_SERVICE="newsletter-digest-anthropic"

# ---- Preconditions: refuse to install a job that cannot work ----
if [ ! -f "$PROJECT_DIR/config.yaml" ]; then
    echo "ERROR: $PROJECT_DIR/config.yaml not found." >&2
    exit 1
fi
if [ ! -f "$PROJECT_DIR/credentials.json" ]; then
    echo "ERROR: $PROJECT_DIR/credentials.json not found. Download the Gmail" >&2
    echo "OAuth Desktop client JSON first (SETUP.md, step 1)." >&2
    exit 1
fi
if ! security find-generic-password -s "$KEYCHAIN_SERVICE" >/dev/null 2>&1; then
    echo "ERROR: no Keychain item '$KEYCHAIN_SERVICE'. Add the Anthropic key first:" >&2
    echo "  security add-generic-password -a \"\$USER\" -s $KEYCHAIN_SERVICE \\" >&2
    echo "      -l \"newsletter-digest Anthropic API key\" -w \"<your key>\" -U" >&2
    exit 1
fi

mkdir -p "$APP_DIR" "$LOG_DIR" "$HOME/Library/LaunchAgents"

# ---- Python venv outside iCloud ----
if [ ! -x "$VENV_DIR/bin/python" ]; then
    BASE_PYTHON="$(command -v python3 || true)"
    if [ -z "$BASE_PYTHON" ]; then
        echo "ERROR: python3 not found on PATH." >&2
        exit 1
    fi
    echo "Creating venv at $VENV_DIR (using $BASE_PYTHON)..."
    "$BASE_PYTHON" -m venv "$VENV_DIR"
fi
echo "Installing/updating requirements..."
"$VENV_DIR/bin/python" -m pip install --quiet --upgrade pip
"$VENV_DIR/bin/python" -m pip install --quiet -r "$PROJECT_DIR/requirements.txt"

# ---- Runner script (generated; values baked in at install time) ----
cat > "$RUNNER" <<RUNNER
#!/bin/bash
# Generated by $PROJECT_DIR/install-launchd.sh on $(date '+%Y-%m-%d %H:%M').
# Re-run the installer instead of editing this file.
set -uo pipefail

PROJECT_DIR="$PROJECT_DIR"
REPO_DIR="$REPO_DIR"
PYTHON="$VENV_DIR/bin/python"
# Fallbacks if the venv under ~/Library was removed.
if [ ! -x "\$PYTHON" ]; then PYTHON="\$PROJECT_DIR/.venv/bin/python"; fi
if [ ! -x "\$PYTHON" ]; then PYTHON="\$(command -v python3)"; fi

# launchd's PATH is minimal; include Homebrew so the usual git (and its
# credential helper) is found.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PYTHONUNBUFFERED=1
# Never let git sit waiting for a password prompt nobody can answer.
export GIT_TERMINAL_PROMPT=0

notify_failure() {
    # A macOS notification, so a failed run is never silent.
    osascript -e "display notification \"\$1 See ~/Library/Logs/newsletter-digest/digest.log\" with title \"Newsletter digest failed\"" >/dev/null 2>&1 || true
}

echo
echo "=== \$(date '+%Y-%m-%d %H:%M:%S') run.sh \$* ==="
cd "\$PROJECT_DIR" || { echo "ERROR: cannot cd to \$PROJECT_DIR"; exit 1; }

# Pull iCloud-evicted files back to disk: the project, the dashboard data it
# rewrites, and the git metadata the publish step reads.
if command -v brctl >/dev/null 2>&1; then
    for path in "\$PROJECT_DIR" "\$REPO_DIR/trends-dashboard/data" "\$REPO_DIR/.git"; do
        brctl download "\$path" >/dev/null 2>&1 || true
    done
fi

is_ready() {
    # A real, readable file (not an iCloud "dataless" placeholder).
    [ -f "\$1" ] && ! ls -lO "\$1" 2>/dev/null | grep -q dataless && head -c 1 "\$1" >/dev/null 2>&1
}
required=("\$PROJECT_DIR/config.yaml" "\$PROJECT_DIR/credentials.json")
if [ -e "\$PROJECT_DIR/token.json" ]; then required+=("\$PROJECT_DIR/token.json"); fi
# Right after a wake from sleep the network and iCloud can take minutes to
# come back, so keep asking for each missing file for up to 15 minutes.
for _ in \$(seq 1 90); do
    all_ready=1
    for f in "\${required[@]}"; do
        if ! is_ready "\$f"; then
            all_ready=0
            command -v brctl >/dev/null 2>&1 && brctl download "\$f" >/dev/null 2>&1
        fi
    done
    [ "\$all_ready" = 1 ] && break
    sleep 10
done
for f in "\${required[@]}"; do
    if ! is_ready "\$f"; then
        echo "ERROR: \$f is still not readable after 15 minutes. Giving up."
        echo "  ls -lO: \$(ls -lO "\$f" 2>&1)"
        echo "  read:   \$(head -c 1 "\$f" 2>&1 >/dev/null || true)"
        echo "  ('dataless' above = iCloud evicted it; 'Operation not permitted' = macOS"
        echo "   privacy is blocking background access to ~/Documents.)"
        notify_failure "iCloud had not downloaded \$(basename "\$f")."
        exit 1
    fi
done

ANTHROPIC_API_KEY="\$(security find-generic-password -s $KEYCHAIN_SERVICE -w 2>/dev/null)"
if [ -z "\$ANTHROPIC_API_KEY" ]; then
    echo "ERROR: could not read Keychain item $KEYCHAIN_SERVICE (is the login keychain locked?)."
    notify_failure "Could not read the Anthropic key from Keychain."
    exit 1
fi
export ANTHROPIC_API_KEY

"\$PYTHON" -u main.py "\$@"
status=\$?
echo "=== \$(date '+%Y-%m-%d %H:%M:%S') exit \$status ==="
if [ "\$status" != 0 ]; then notify_failure "The run exited with code \$status."; fi
exit \$status
RUNNER
chmod 700 "$RUNNER"

# ---- launchd job ----
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true

cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$RUNNER</string>
    </array>
    <!-- Start outside iCloud; the runner cds into the project itself. -->
    <key>WorkingDirectory</key>
    <string>$APP_DIR</string>
    <!-- Unbuffered so a crash lands in the log instead of dying in
         Python's stdout buffer (block-buffered when stdout is a file). -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PYTHONUNBUFFERED</key>
        <string>1</string>
    </dict>
    <key>StartCalendarInterval</key>
    <array>
        <dict>
            <key>Weekday</key>
            <integer>3</integer>
            <key>Hour</key>
            <integer>8</integer>
            <key>Minute</key>
            <integer>0</integer>
        </dict>
        <dict>
            <key>Weekday</key>
            <integer>5</integer>
            <key>Hour</key>
            <integer>8</integer>
            <key>Minute</key>
            <integer>0</integer>
        </dict>
    </array>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$LOG_FILE</string>
    <key>StandardErrorPath</key>
    <string>$LOG_FILE</string>
</dict>
</plist>
PLIST

plutil -lint "$PLIST" >/dev/null
launchctl bootstrap "gui/$(id -u)" "$PLIST"
echo "--- launchd status ---"
launchctl print "gui/$(id -u)/$LABEL" | grep -E "state|last exit" || true
echo
echo "Installed $LABEL (Wed/Fri 08:00)."
echo "  Runner: $RUNNER"
echo "  Log:    $LOG_FILE"
if [ ! -f "$PROJECT_DIR/token.json" ]; then
    echo
    echo "Next: do the one-time Gmail consent from this Terminal:"
    echo "  \"$RUNNER\" --dry-run --skip-trends"
fi
