#!/bin/bash
# Installs the newsletter digest as a macOS launchd user agent that runs at
# 8:00 on Wednesdays and Fridays. Re-run any time; it replaces the existing
# job. Uninstall with:
#   launchctl bootout "gui/$(id -u)/com.bexperiments.newsletter-digest"
#   rm ~/Library/LaunchAgents/com.bexperiments.newsletter-digest.plist
#
# Same layout as agent-team/install-launchd.sh, for the same reason: the repo
# is in iCloud-synced ~/Documents and "Optimize Mac Storage" evicts idle files
# to dataless placeholders that a launchd-spawned process cannot read back.
# So the venv, the runner script and the log all live under ~/Library, which
# is not iCloud-synced. The Anthropic key is read from the login Keychain by
# the runner; it is never written into the plist.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
LABEL="com.bexperiments.newsletter-digest"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG_DIR="$HOME/Library/Logs/newsletter-digest"
LOG_FILE="$LOG_DIR/digest.log"
APP_DIR="$HOME/Library/Application Support/newsletter-digest"
VENV_DIR="$APP_DIR/.venv"
PYTHON="$VENV_DIR/bin/python"
RUNNER="$APP_DIR/run.sh"
KEYCHAIN_SERVICE="newsletter-digest-anthropic"

mkdir -p "$APP_DIR" "$LOG_DIR" "$HOME/Library/LaunchAgents"

if [ ! -x "$PYTHON" ]; then
    echo "No external venv at $VENV_DIR; creating it (out of iCloud)..."
    BASE_PY="$(command -v python3.13 || command -v python3)"
    "$BASE_PY" -m venv "$VENV_DIR"
    "$PYTHON" -m pip install --quiet --upgrade pip
    "$PYTHON" -m pip install --quiet -r "$PROJECT_DIR/requirements.txt"
fi

for f in config.yaml credentials.json; do
    if [ ! -f "$PROJECT_DIR/$f" ]; then
        echo "ERROR: $PROJECT_DIR/$f not found. Set it up first." >&2
        exit 1
    fi
done

if ! security find-generic-password -s "$KEYCHAIN_SERVICE" >/dev/null 2>&1; then
    cat >&2 <<MSG
ERROR: no Keychain item for service '$KEYCHAIN_SERVICE'. Create it with:
  security add-generic-password -a "\$USER" -s $KEYCHAIN_SERVICE \\
      -l "newsletter-digest Anthropic API key" -w "<your key>" -U
MSG
    exit 1
fi

# The launchd entry point must ALSO live outside iCloud. Generate it with the
# real repo path and interpreter baked in — a verbatim copy of run.sh would
# resolve its own dir ($0) to ~/Library and miss main.py.
cat > "$RUNNER" <<RUNNER_EOF
#!/bin/bash
# GENERATED by install-launchd.sh — edit newsletter-digest/run.sh and re-run installer.
# Materializes the iCloud-evicted repo before launching the out-of-iCloud
# interpreter, with the Anthropic key pulled from the login Keychain.
set -euo pipefail
PROJECT_DIR="$PROJECT_DIR"
VENV_PY="$PYTHON"
cd "\$PROJECT_DIR"
brctl download "\$PROJECT_DIR" >/dev/null 2>&1 || true
for f in config.yaml credentials.json token.json; do
    for _ in \$(seq 1 60); do
        case "\$(stat -f '%Sf' "\$PROJECT_DIR/\$f" 2>/dev/null)" in
            *dataless*) brctl download "\$PROJECT_DIR/\$f" >/dev/null 2>&1 || true; sleep 1 ;;
            *) break ;;
        esac
    done
done
ANTHROPIC_API_KEY="\$(security find-generic-password -s "$KEYCHAIN_SERVICE" -w)"
if [ -z "\$ANTHROPIC_API_KEY" ]; then
    echo "ERROR: no Keychain item for service '$KEYCHAIN_SERVICE'" >&2
    exit 78
fi
export ANTHROPIC_API_KEY
exec "\$VENV_PY" main.py "\$@"
RUNNER_EOF
chmod +x "$RUNNER"

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true

cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$RUNNER</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$PROJECT_DIR</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>PYTHONUNBUFFERED</key>
        <string>1</string>
    </dict>
    <!-- 8:00 on Wednesdays (3) and Fridays (5). -->
    <key>StartCalendarInterval</key>
    <array>
        <dict>
            <key>Weekday</key>
            <integer>3</integer>
            <key>Hour</key>
            <integer>8</integer>
            <key>Minute</key>
            <integer>0</integer>
        </dict>
        <dict>
            <key>Weekday</key>
            <integer>5</integer>
            <key>Hour</key>
            <integer>8</integer>
            <key>Minute</key>
            <integer>0</integer>
        </dict>
    </array>
    <key>StandardOutPath</key>
    <string>$LOG_FILE</string>
    <key>StandardErrorPath</key>
    <string>$LOG_FILE</string>
</dict>
</plist>
PLIST

launchctl bootstrap "gui/$(id -u)" "$PLIST"
sleep 1
echo "--- launchd status ---"
launchctl print "gui/$(id -u)/$LABEL" | grep -E "state|program|last exit" || true
echo
echo "Installed. Next runs: Wed/Fri 08:00. Log: $LOG_FILE"
echo "Manual run: $RUNNER --dry-run --skip-trends"
