#!/bin/bash
# Installs the newsletter digest as a macOS launchd user agent for the
# Wednesday and Friday 08:00 digest. launchd starts the runner every 30
# minutes and on wake; schedule_guard.py decides whether a slot is due, so a
# digest missed while the Mac was asleep, shut or offline goes out shortly
# after it is back instead of being skipped. Optionally also schedules the Mac
# to wake at 07:55 on those days. See SETUP.md for the full picture.
#
# Everything launchd needs at spawn time lives under ~/Library, which iCloud
# does not sync: the venv, the generated runner script and the log. The repo
# itself sits in iCloud-synced ~/Documents, where "Optimize Mac Storage"
# evicts idle files to dataless placeholders that a launchd process cannot
# read (EDEADLK), so the runner rematerializes what it needs before starting
# Python.
#
# Re-run any time; it replaces the existing job. Uninstall with:
#   launchctl bootout "gui/$(id -u)/com.bexperiments.newsletter-digest"
#   rm ~/Library/LaunchAgents/com.bexperiments.newsletter-digest.plist
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
LABEL="com.bexperiments.newsletter-digest"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
APP_DIR="$HOME/Library/Application Support/newsletter-digest"
VENV_DIR="$APP_DIR/.venv"
RUNNER="$APP_DIR/run.sh"
LOG_DIR="$HOME/Library/Logs/newsletter-digest"
LOG_FILE="$LOG_DIR/digest.log"
KEYCHAIN_SERVICE="newsletter-digest-anthropic"
GUARD="$APP_DIR/schedule_guard.py"
STATE_FILE="$APP_DIR/last-digest-slot"

# ---- Preconditions: refuse to install a job that cannot work ----
if [ ! -f "$PROJECT_DIR/config.yaml" ]; then
    echo "ERROR: $PROJECT_DIR/config.yaml not found." >&2
    exit 1
fi
if [ ! -f "$PROJECT_DIR/credentials.json" ]; then
    echo "ERROR: $PROJECT_DIR/credentials.json not found. Download the Gmail" >&2
    echo "OAuth Desktop client JSON first (SETUP.md, step 1)." >&2
    exit 1
fi
if ! security find-generic-password -s "$KEYCHAIN_SERVICE" >/dev/null 2>&1; then
    echo "ERROR: no Keychain item '$KEYCHAIN_SERVICE'. Add the Anthropic key first:" >&2
    echo "  security add-generic-password -a \"\$USER\" -s $KEYCHAIN_SERVICE \\" >&2
    echo "      -l \"newsletter-digest Anthropic API key\" -w \"<your key>\" -U" >&2
    exit 1
fi

mkdir -p "$APP_DIR" "$LOG_DIR" "$HOME/Library/LaunchAgents"

# ---- Python venv outside iCloud ----
if [ ! -x "$VENV_DIR/bin/python" ]; then
    BASE_PYTHON="$(command -v python3 || true)"
    if [ -z "$BASE_PYTHON" ]; then
        echo "ERROR: python3 not found on PATH." >&2
        exit 1
    fi
    echo "Creating venv at $VENV_DIR (using $BASE_PYTHON)..."
    "$BASE_PYTHON" -m venv "$VENV_DIR"
fi
echo "Installing/updating requirements..."
"$VENV_DIR/bin/python" -m pip install --quiet --upgrade pip
"$VENV_DIR/bin/python" -m pip install --quiet -r "$PROJECT_DIR/requirements.txt"

# The schedule check runs every 30 minutes, so keep a copy outside iCloud
# where reading it never needs a download.
cp "$PROJECT_DIR/schedule_guard.py" "$GUARD"

# ---- Runner script (generated; values baked in at install time) ----
cat > "$RUNNER" <<RUNNER
#!/bin/bash
# Generated by $PROJECT_DIR/install-launchd.sh on $(date '+%Y-%m-%d %H:%M').
# Re-run the installer instead of editing this file.
set -uo pipefail

PROJECT_DIR="$PROJECT_DIR"
REPO_DIR="$REPO_DIR"
PYTHON="$VENV_DIR/bin/python"
# Fallbacks if the venv under ~/Library was removed.
if [ ! -x "\$PYTHON" ]; then PYTHON="\$PROJECT_DIR/.venv/bin/python"; fi
if [ ! -x "\$PYTHON" ]; then PYTHON="\$(command -v python3)"; fi
GUARD="$GUARD"
STATE_FILE="$STATE_FILE"
# main.py records the slot here as soon as the email is sent.
export NEWSLETTER_DIGEST_STATE="\$STATE_FILE"

# launchd passes --scheduled every 30 minutes and on wake. Exit quietly
# unless the latest Wed/Fri 08:00 slot has not been sent yet; a failed run
# stays due and is retried on the next check. Manual runs skip this check.
SCHEDULED=0
if [ "\${1:-}" = "--scheduled" ]; then
    SCHEDULED=1
    shift
    "\$PYTHON" "\$GUARD" due "\$STATE_FILE" >/dev/null 2>&1 || exit 0
fi

# launchd's PATH is minimal; include Homebrew so the usual git (and its
# credential helper) is found.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PYTHONUNBUFFERED=1
# Never let git sit waiting for a password prompt nobody can answer.
export GIT_TERMINAL_PROMPT=0

echo
echo "=== \$(date '+%Y-%m-%d %H:%M:%S') run.sh \$* ==="
cd "\$PROJECT_DIR" || { echo "ERROR: cannot cd to \$PROJECT_DIR"; exit 1; }

# Pull iCloud-evicted files back to disk: the project, the dashboard data it
# rewrites, and the git metadata the publish step reads.
if command -v brctl >/dev/null 2>&1; then
    for path in "\$PROJECT_DIR" "\$REPO_DIR/trends-dashboard/data" "\$REPO_DIR/.git"; do
        brctl download "\$path" >/dev/null 2>&1 || true
    done
fi

is_ready() {
    # A real, readable file (not an iCloud "dataless" placeholder).
    [ -f "\$1" ] && ! ls -lO "\$1" 2>/dev/null | grep -q dataless && head -c 1 "\$1" >/dev/null 2>&1
}
required=("\$PROJECT_DIR/config.yaml" "\$PROJECT_DIR/credentials.json")
if [ -e "\$PROJECT_DIR/token.json" ]; then required+=("\$PROJECT_DIR/token.json"); fi
for _ in \$(seq 1 60); do
    all_ready=1
    for f in "\${required[@]}"; do is_ready "\$f" || all_ready=0; done
    [ "\$all_ready" = 1 ] && break
    sleep 2
done
for f in "\${required[@]}"; do
    if ! is_ready "\$f"; then
        echo "ERROR: \$f is still not available locally (iCloud). Giving up."
        exit 1
    fi
done

ANTHROPIC_API_KEY="\$(security find-generic-password -s $KEYCHAIN_SERVICE -w 2>/dev/null)"
if [ -z "\$ANTHROPIC_API_KEY" ]; then
    echo "ERROR: could not read Keychain item $KEYCHAIN_SERVICE (is the login keychain locked?)."
    exit 1
fi
export ANTHROPIC_API_KEY

# caffeinate keeps the Mac from idling back to sleep mid-run (for example
# after a scheduled wake).
/usr/bin/caffeinate -i "\$PYTHON" -u main.py "\$@"
status=\$?
if [ "\$SCHEDULED" = 1 ] && [ "\$status" = 0 ]; then
    "\$PYTHON" "\$GUARD" mark "\$STATE_FILE"
fi
echo "=== \$(date '+%Y-%m-%d %H:%M:%S') exit \$status ==="
exit \$status
RUNNER
chmod 700 "$RUNNER"

# ---- launchd job ----
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true

cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$RUNNER</string>
        <string>--scheduled</string>
    </array>
    <!-- Start outside iCloud; the runner cds into the project itself. -->
    <key>WorkingDirectory</key>
    <string>$APP_DIR</string>
    <!-- Unbuffered so a crash lands in the log instead of dying in
         Python's stdout buffer (block-buffered when stdout is a file). -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PYTHONUNBUFFERED</key>
        <string>1</string>
    </dict>
    <!-- Check every 30 minutes, at load and after wake (launchd fires a
         missed interval once on wake). The runner only does real work when
         a Wed/Fri 08:00 slot is due and unsent. -->
    <key>StartInterval</key>
    <integer>1800</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$LOG_FILE</string>
    <key>StandardErrorPath</key>
    <string>$LOG_FILE</string>
</dict>
</plist>
PLIST

plutil -lint "$PLIST" >/dev/null
launchctl bootstrap "gui/$(id -u)" "$PLIST"
echo "--- launchd status ---"
launchctl print "gui/$(id -u)/$LABEL" | grep -E "state|last exit" || true
echo
echo "Installed $LABEL (Wed/Fri 08:00; catches up within 30 minutes of wake)."
echo "  Runner: $RUNNER"
echo "  Log:    $LOG_FILE"
echo "  State:  $STATE_FILE"

# ---- Optional: wake the Mac for the 08:00 slot ----
if [ -t 0 ]; then
    echo
    echo "Current power schedule (pmset -g sched):"
    pmset -g sched 2>/dev/null | sed 's/^/  /' || true
    read -r -p "Wake the Mac at 07:55 Wed/Fri so the digest is on time even when asleep? This replaces any repeating schedule above and asks for your password. [y/N] " answer
    case "$answer" in
        [yY]*) sudo pmset repeat wakeorpoweron WF 07:55:00 && pmset -g sched ;;
        *) echo "Skipped. Missed slots still go out within 30 minutes of the next wake." ;;
    esac
fi
if [ ! -f "$PROJECT_DIR/token.json" ]; then
    echo
    echo "Next: do the one-time Gmail consent from this Terminal:"
    echo "  \"$RUNNER\" --dry-run --skip-trends"
fi
